### GET request to /api/stockEntries
GET http://localhost/api/stockEntries
###

### POST request to /api/stockEntries
POST http://localhost/api/stockEntries
Accept: application/json
Content-Type: application/json

{
    "inventory_log_id": 24,
    "stock_item_id": 9,
    "quantity": 100,
    "cost": 99.99,
    "cost_per_unit": 1
}
###

### GET request to /api/stockEntries/{id}
GET http://localhost/api/stockEntries/41
Accept: application/json
###

### PUT request to /api/stockEntries/{id}
PUT http://localhost/api/stockEntries/41
Accept: application/json
Content-Type: application/json

{
    "stock_item_id": 51,
    "inventory_log_id": 11,
    "cost": 200,
    "cost_per_unit": 0,
    "quantity": 70
}
###

### DELETE request to /api/stockEntries/{id}
DELETE http://localhost/api/stockEntries/41
Accept: application/json

###
