### GET request to /api/stockItems
GET http://localhost/api/stockItems
###

### POST request to /api/stockItems
POST http://localhost/api/stockItems
Accept: application/json
Content-Type: application/json

{
    "name" : "ไก่ย่าง",
    "category": "ผัก",
    "current_stock": 0,
    "unit": "กิโลกรัม"
}
###

### GET request to /api/stockItems/{id}
GET http://localhost/api/stockItems/59
Accept: application/json
###

### PUT request to /api/stockItems/{id}
PUT http://localhost/api/stockItems/56
Accept: application/json
Content-Type: application/json

{
    "name" : "ปู",
    "category": "ผัก",
    "current_stock": 0,
    "unit": "กก."
}
###

### DELETE request to /api/stockItems/{id}
DELETE http://localhost/api/stockItems/19
Accept: application/json

###
